# Copyright 2011 Ivan Krasin. All rights reserved.

include $(GOROOT)/src/Make.inc

TARG=optimize
GOFILES=\
	octree.go\
	optimize.go\
	sparse_volume.go\
	stl_reader.go\
	timing.go\
	triangle.go\

include $(GOROOT)/src/Make.cmd
